"""empty message

Revision ID: 07afbb1e55f7
Revises: c235ce30ac11
Create Date: 2024-12-19 11:02:40.130358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07afbb1e55f7'
down_revision = 'c235ce30ac11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quoted_post_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_post_quoted_post_id_post'), 'post', ['quoted_post_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_post_quoted_post_id_post'), type_='foreignkey')
        batch_op.drop_column('quoted_post_id')

    # ### end Alembic commands ###
